export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_SUCCESS = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_SUCCESS';
export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_ERROR = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_ERROR';
export const UPDATE_KEYPAIR_TYPE = 'ACCOUNT/UPDATE_KEYPAIR_TYPE';
export const CREATE_DUPLICATE_ALIAS_ERROR = 'ACCOUNT/CREATE_DUPLICATE_ALIAS_ERROR';
