export const TERMS_PAGE = 'TERMS_PAGE';
export const ENTRY_PAGE = 'ENTRY_PAGE';
export const IMPORT_WALLET_PAGE = 'IMPORT_WALLET_PAGE';
export const DASHBOARD_PAGE = 'DASHBOARD_PAGE';
export const TRANSFER_PAGE = 'TRANSFER_PAGE';
export const CONFIRM_PAGE = 'CONFIRM_PAGE';
export const TRANSFER_STATUS_PAGE = 'TRANSFER_STATUS_PAGE';
export const SIGN_UP_PAGE = 'SIGN_UP_PAGE';
export const SIGN_IN_PAGE = 'SIGN_IN_PAGE';
export const LOADER_OVERLAY = 'LOADER_OVERLAY';
export const CREATE_ACCOUNT_PAGE = 'CREATE_ACCOUNT_PAGE';
export const ERROR_PAGE = 'ERROR_PAGE';
export const CUSTOM_NETWORK_PAGE = 'CUSTOM_NETWORK_PAGE';
export const QR_CODE_PAGE = 'QR_CODE_PAGE';
export const MANAGE_ACCOUNT_PAGE = 'manage_account';
export const ABOUT_PAGE = 'about';
export const CONNECT_REQUEST_PAGE = 'connectRequest';
export const DAPP_REQUESTS_PAGE = 'DAPP_REQUESTS_PAGE';
export const CREATE_ADDRESS_BOOK_PAGE = 'CREATE_ADDRESS_BOOK_PAGE';DASHBOARD_PAGE
export const ADDRESS_BOOK_PAGE = 'address_book';
export const NODE_SETTING_PAGE = 'NODE_SETTING';
export const NODE_LIST_PAGE = 'NODE_LIST_PAGE';
export const CHAIN_PAGE = 'CHAIN_PAGE';
export const TRADE_PAGE = 'TRADE_PAGE';
export const ADD_TOKEN_PAGE = 'ADD_TOKEN_PAGE';
export const SETTINGS_PAGE = 'SETTINGS_PAGE';
export const DAPP_WEB3_REQUESTS_PAGE = 'DAPP_WEB3_REQUESTS_PAGE';
export const CHAINS_PAGE = 'CHAINS_PAGE';

export const ONBOARDING_PAGES_GROUP = [
  TERMS_PAGE,
  SIGN_IN_PAGE,
  SIGN_UP_PAGE,
  CREATE_ACCOUNT_PAGE,
  IMPORT_WALLET_PAGE,
];

export const DISABLE_NETWORKS_PAGES_GROUP = [
  ADDRESS_BOOK_PAGE,
  NODE_SETTING_PAGE,
  MANAGE_ACCOUNT_PAGE,
  CONNECT_REQUEST_PAGE,
  DAPP_REQUESTS_PAGE,
  CONFIRM_PAGE,
];

export const DISABLE_SETTINGS_PAGES_GROUP = [CONNECT_REQUEST_PAGE, DAPP_REQUESTS_PAGE];
