export const CONNECT_REQUEST_ALLOW_AUTHORIZE = 'CONNECT_REQUEST/ALLOW_AUTHORIZE';
export const CONNECT_REQUEST_ACCOUNT_OPTIONS = 'CONNECT_REQUEST/ACCOUNT_OPTIONS';
export const CONNECT_REQUEST_SELECTED_ACCOUNT = 'CONNECT_REQUEST/SELECTED_ACCOUNT';
export const CONNECT_REQUEST_TITLE = 'CONNECT_REQUEST/TITLE';
