export const COIN_TRANSFER_DETAILS = 'TRANSFER/DETAILS';
export const CLEAR_COIN_TRANSFER_DETAILS = 'TRANSFER/CLEAR_DETAILS';
export const CONFIRM_TRANSFER_SUCCESS = 'TRANSFER/CONFIRM_SUCCESS';
export const CONFIRM_TRANSFER_ERROR = 'TRANSFER/CONFIRM_ERROR';
export const SET_TRANSFER_VALIDATION_ERROR = 'TRANSFER/SET_VALIDATION_ERROR';
